/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'albert' at '05/02/18 13:26' with Gradle 2.10
 *
 * @author albert, @date 05/02/18 13:26
 */
public class Library {
    
    public int fib(int n) {
        if(n <= 1) {
			return n;
		}
		int fib = 1;
		int prevFib = 1;
		for(int i=2; i<n; i++) {
			int temp = fib;
			fib+= prevFib;
			prevFib = temp;
		}
		return fib;
    }
}
