import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'albert' at '05/02/18 13:26' with Gradle 2.10
 *
 * @author albert, @date 05/02/18 13:26
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertEquals(50, classUnderTest.fib(10));
    }
}
